name: Continuous Integration

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout OpenChrom Thirdparty
      uses: actions/checkout@v3
      with:
        path: openchrom3rdparty
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: cd openchrom3rdparty && mvn -f openchrom/cbi/net.openchrom.thirdpartylibraries.cbi/pom.xml install --batch-mode --no-transfer-progress
