name: Continuous Integration
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ChemClipse
      uses: actions/checkout@v2
      with:
        path: chemclipse
        repository: 'eclipse/chemclipse'
    - name: Checkout OpenChrom Thirdparty
      uses: actions/checkout@v2
      with:
        path: openchrom3rdparty
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: cd openchrom3rdparty && mvn -f openchrom/cbi/net.openchrom.thirdpartylibraries.cbi/pom.xml install --batch-mode --no-transfer-progress
